export {
  CockpitSlicesSchema,
  CockpitStudioItemSchema,
  CockpitCalendarItemSchema,
  CockpitReportItemSchema,
  CockpitResearchItemSchema,
  CockpitStudioPanelSchema,
  CockpitCalendarPanelSchema,
  CockpitReportsPanelSchema,
  CockpitResearchPanelSchema,
  type CockpitSlices,
  type CockpitStudioItem,
  type CockpitCalendarItem,
  type CockpitReportItem,
  type CockpitResearchItem,
} from "./cockpit.js";
